### ISSUE TITLE
ERROR: local variable 'module_content' referenced before assignment

### ISSUE THREAD

**Issue by jznling** [Azure/iotedgehubdev#195]
I run this project on a Windows 10 OS, Docker 4.0.1, surface pro 4.

I followed the procedure of deploying OPC Twin to IoT Edge on https://docs.microsoft.com/en-us/azure/iot-accelerators/howto-opc-twin-deploy-modules

When I proceed to start deployment using iotedgehubdev in "run and debug locally" section, my PowerShell alert with a warning " ERROR: local variable 'module_content' referenced before assignment ".

It seems like a coding problem to me. Maybe a global-local variable problem or uninitialized variable access. 

Well, I had the same problem "Docker 4.0.1 Incompatible w/ Docker-Compose 1.24.0". I didn't deal with this problem when I saw the iotedgehubdev in my pip list. Could this be the reason?

Please reply to me if you have any clue to fix it.

**Comment by jznling** [comment]
I reinstall the iotedgehubdev successfully using the solution in #190, and retry the method "iotedgehubdev start -d deployment.json".
The same warning comes out again, "ERROR: local variable 'module_content' referenced before assignment".

**Comment by adashen** [comment]
@jznling The potential reason is your deployment.json may don't have "modulesContent" schema. Can you check the deployment manifest again? Or can you send the deployment.json to us?

**Comment by jznling** [comment]
@adashen Well, it is the deployment.json problem. In the webpage I provided, there is a required deployment manifesto copied to deployment.json. 
![image](https://user-images.githubusercontent.com/8361314/59589706-2279d680-911d-11e9-981b-6b9fb7215e2b.png)
![image](https://user-images.githubusercontent.com/8361314/59590000-acc23a80-911d-11e9-8c52-4f115eba5dfd.png)
As you can see, it made 'content' as the index and easily skip the if-statement for acquiring the module content in cli.py. I suggested to add an else statement after the if statement in case further unexpected mistake. 
However, I got another error after fixing this. 
"ERROR: 'network_mode' and 'networks' cannot be combined
ERROR: Error while executing command: docker-compose -f C:\ProgramData\iotedgehubdev\data\data\docker-compose.yml pull edgeHubDev. Command '['docker-compose', '-f', 'C:\\ProgramData\\iotedgehubdev\\data\\data\\docker-compose.yml', 'pull', 'edgeHubDev']' returned non-zero exit status 1. "
I attached a shortcut of my docker-compose.yml. Could you help me fix it?
![image](https://user-images.githubusercontent.com/8361314/59590453-b304e680-911e-11e9-949b-edb046ec2b43.png)

**Comment by adashen** [comment]
@jznling Thanks for the suggestion. As for the network issue, host mode is not supported currently. And there is already one issue .in the backlog https://github.com/Azure/iotedgehubdev/issues/183

Can you provide the scenario that you need the host mode network?

**Comment by jznling** [comment]
@adashen Well, I don't really understand "We need add azure-iot-edge-dev network only user doesn't config network." in backlog #183 
I am doing an OPC Twin demo as the webpage, https://docs.microsoft.com/en-us/azure/iot-accelerators/howto-opc-twin-deploy-modules#run-and-debug-locally
I am planning to use it to monitor some device condition.

**Comment by jznling** [comment]
@adashen Do you mean I need to use my own network port for the demo?  To which part?

**Comment by jznling** [comment]
@adashen I copied the result of docker-compose.yml here. 
`version: '3.6'
services:
  edgeHubDev:
    container_name: edgeHubDev
    environment:
    - routes__r1=FROM /messages/modules/opctwin/* INTO $$upstream
    - routes__r2=FROM /messages/modules/opcpublisher/* INTO $$upstream
    - IotHubConnectionString=          ###myconnectionstring###
    - EdgeModuleHubServerCAChainCertificateFile=/mnt/edgehub/edge-chain-ca.cert.pem
    - EdgeModuleHubServerCertificateFile=/mnt/edgehub/edge-hub-server.cert.pfx
    - configSource=local
    - SSL_CERTIFICATE_PATH=/mnt/edgehub/
    - SSL_CERTIFICATE_NAME=edge-hub-server.cert.pfx
    image: mcr.microsoft.com/azureiotedge-hub:1.0
    labels:
      iotedgehubdev: ''
    networks:
      azure-iot-edge-dev:
        aliases:
        -       ###myusername###
    ports:
    - 5671:5671/tcp
    - 8883:8883/tcp
    - 443:443/tcp
    restart: always
    volumes:
    - source: edgehubdev
      target: /mnt/edgehub
      type: volume
  opctwin:
    cap_add:
    - NET_ADMIN
    container_name: opctwin
    depends_on:
    - edgeHubDev
    environment:
    - EdgeModuleCACertificateFile=/mnt/edgemodule/edge-device-ca.cert.pem
    - EdgeHubConnectionString=          ###myconnectionstring###
    image: mcr.microsoft.com/iotedge/opc-twin:latest
    labels:
      iotedgehubdev: ''
    network_mode: host
    networks:
      azure-iot-edge-dev: null
      host: {}
    restart: always
    volumes:
    - source: edgemoduledev
      target: /mnt/edgemodule
      type: volume
  opcpublisher:
    command: publisher --pf=./pn.json --di=60 --to --aa --si=0 --ms=0
    container_name: opcpublisher
    depends_on:
    - edgeHubDev
    environment:
    - EdgeModuleCACertificateFile=/mnt/edgemodule/edge-device-ca.cert.pem
    - EdgeHubConnectionString=          ###myconnectionstring###
    expose:
    - 62222/tcp
    hostname: publisher
    image: mcr.microsoft.com/iotedge/opc-publisher:latest
    labels:
      iotedgehubdev: ''
    network_mode: host
    networks:
      azure-iot-edge-dev: null
      host: {}
    ports:
    - 62222:62222/tcp
    restart: always
    volumes:
    - source: edgemoduledev
      target: /mnt/edgemodule
      type: volume
networks:
  azure-iot-edge-dev:
    external: true
  host:
    external: true
volumes:
  edgehubdev:
    name: edgehubdev
  edgemoduledev:
    name: edgemoduledev
`

**Comment by jznling** [comment]
@adashen I add the content of docker-compse.yml here. The content is generated by iotedgehubdev setup and start.
'''
version: '3.6'
services:
  edgeHubDev:
    container_name: edgeHubDev
    environment:
    - routes__r1=FROM /messages/modules/opctwin/* INTO $$upstream
    - routes__r2=FROM /messages/modules/opcpublisher/* INTO $$upstream
    - IotHubConnectionString=          ###myconnectionstring###
    - EdgeModuleHubServerCAChainCertificateFile=/mnt/edgehub/edge-chain-ca.cert.pem
    - EdgeModuleHubServerCertificateFile=/mnt/edgehub/edge-hub-server.cert.pfx
    - configSource=local
    - SSL_CERTIFICATE_PATH=/mnt/edgehub/
    - SSL_CERTIFICATE_NAME=edge-hub-server.cert.pfx
    image: mcr.microsoft.com/azureiotedge-hub:1.0
    labels:
      iotedgehubdev: ''
    networks:
      azure-iot-edge-dev:
        aliases:
        -       ###myusername###
    ports:
    - 5671:5671/tcp
    - 8883:8883/tcp
    - 443:443/tcp
    restart: always
    volumes:
    - source: edgehubdev
      target: /mnt/edgehub
      type: volume
  opctwin:
    cap_add:
    - NET_ADMIN
    container_name: opctwin
    depends_on:
    - edgeHubDev
    environment:
    - EdgeModuleCACertificateFile=/mnt/edgemodule/edge-device-ca.cert.pem
    - EdgeHubConnectionString=          ###myconnectionstring###
    image: mcr.microsoft.com/iotedge/opc-twin:latest
    labels:
      iotedgehubdev: ''
    network_mode: host
    networks:
      azure-iot-edge-dev: null
      host: {}
    restart: always
    volumes:
    - source: edgemoduledev
      target: /mnt/edgemodule
      type: volume
  opcpublisher:
    command: publisher --pf=./pn.json --di=60 --to --aa --si=0 --ms=0
    container_name: opcpublisher
    depends_on:
    - edgeHubDev
    environment:
    - EdgeModuleCACertificateFile=/mnt/edgemodule/edge-device-ca.cert.pem
    - EdgeHubConnectionString=          ###myconnectionstring###
    expose:
    - 62222/tcp
    hostname: publisher
    image: mcr.microsoft.com/iotedge/opc-publisher:latest
    labels:
      iotedgehubdev: ''
    network_mode: host
    networks:
      azure-iot-edge-dev: null
      host: {}
    ports:
    - 62222:62222/tcp
    restart: always
    volumes:
    - source: edgemoduledev
      target: /mnt/edgemodule
      type: volume
networks:
  azure-iot-edge-dev:
    external: true
  host:
    external: true
volumes:
  edgehubdev:
    name: edgehubdev
  edgemoduledev:
    name: edgemoduledev
'''

**Comment by jznling** [comment]
I add the content of docker-compse.yml here. The content is generated by iotedgehubdev setup and start.

``` YAML
version:` '3.6'
services:
edgeHubDev:
container_name: edgeHubDev
environment:
- routes__r1=FROM /messages/modules/opctwin/* INTO $$upstream
- routes__r2=FROM /messages/modules/opcpublisher/* INTO $$upstream
- IotHubConnectionString= ###myconnectionstring###
- EdgeModuleHubServerCAChainCertificateFile=/mnt/edgehub/edge-chain-ca.cert.pem
- EdgeModuleHubServerCertificateFile=/mnt/edgehub/edge-hub-server.cert.pfx
- configSource=local
- SSL_CERTIFICATE_PATH=/mnt/edgehub/
- SSL_CERTIFICATE_NAME=edge-hub-server.cert.pfx
image: mcr.microsoft.com/azureiotedge-hub:1.0
labels:
iotedgehubdev: ''
networks:
azure-iot-edge-dev:
aliases:
- ###myusername###
ports:
- 5671:5671/tcp
- 8883:8883/tcp
- 443:443/tcp
restart: always
volumes:
- source: edgehubdev
target: /mnt/edgehub
type: volume
opctwin:
cap_add:
- NET_ADMIN
container_name: opctwin
depends_on:
- edgeHubDev
environment:
- EdgeModuleCACertificateFile=/mnt/edgemodule/edge-device-ca.cert.pem
- EdgeHubConnectionString= ###myconnectionstring###
image: mcr.microsoft.com/iotedge/opc-twin:latest
labels:
iotedgehubdev: ''
network_mode: host
networks:
azure-iot-edge-dev: null
host: {}
restart: always
volumes:
- source: edgemoduledev
target: /mnt/edgemodule
type: volume
opcpublisher:
command: publisher --pf=./pn.json --di=60 --to --aa --si=0 --ms=0
container_name: opcpublisher
depends_on:
- edgeHubDev
environment:
- EdgeModuleCACertificateFile=/mnt/edgemodule/edge-device-ca.cert.pem
- EdgeHubConnectionString= ###myconnectionstring###
expose:
- 62222/tcp
hostname: publisher
image: mcr.microsoft.com/iotedge/opc-publisher:latest
labels:
iotedgehubdev: ''
network_mode: host
networks:
azure-iot-edge-dev: null
host: {}
ports:
- 62222:62222/tcp
restart: always
volumes:
- source: edgemoduledev
target: /mnt/edgemodule
type: volume
networks:
azure-iot-edge-dev:
external: true
host:
external: true
volumes:
edgehubdev:
name: edgehubdev
edgemoduledev:
name: edgemoduledev
```

**Comment by jznling** [comment]
I add the content of docker-compse.yml here. The content is generated by iotedgehubdev setup and start. This might help you better figure out the problem. 
``` YAML
version:` '3.6'
services:
    edgeHubDev:
        container_name: edgeHubDev
        environment:
        - routes__r1=FROM /messages/modules/opctwin/* INTO $$upstream
        - routes__r2=FROM /messages/modules/opcpublisher/* INTO $$upstream
        - IotHubConnectionString=                 ###myconnectionstring###
        - EdgeModuleHubServerCAChainCertificateFile=/mnt/edgehub/edge-chain-ca.cert.pem
        - EdgeModuleHubServerCertificateFile=/mnt/edgehub/edge-hub-server.cert.pfx
        - configSource=local
        - SSL_CERTIFICATE_PATH=/mnt/edgehub/
        - SSL_CERTIFICATE_NAME=edge-hub-server.cert.pfx
        image: mcr.microsoft.com/azureiotedge-hub:1.0
        labels:
            iotedgehubdev: ''
        networks:
            azure-iot-edge-dev:
                aliases:
                -                 ###myusername###
        ports:
        - 5671:5671/tcp
        - 8883:8883/tcp
        - 443:443/tcp
        restart: always
        volumes:
        - source: edgehubdev
           target: /mnt/edgehub
           type: volume
    opctwin:
        cap_add:
        - NET_ADMIN
        container_name: opctwin
        depends_on:
        - edgeHubDev
        environment:
        - EdgeModuleCACertificateFile=/mnt/edgemodule/edge-device-ca.cert.pem
        - EdgeHubConnectionString= ###myconnectionstring###
        image: mcr.microsoft.com/iotedge/opc-twin:latest
        labels:
            iotedgehubdev: ''
        network_mode: host
        networks:
            azure-iot-edge-dev: null
            host: {}
        restart: always
        volumes:
        - source: edgemoduledev
           target: /mnt/edgemodule
           type: volume
    opcpublisher:
        command: publisher --pf=./pn.json --di=60 --to --aa --si=0 --ms=0
        container_name: opcpublisher
        depends_on:
        - edgeHubDev
        environment:
        - EdgeModuleCACertificateFile=/mnt/edgemodule/edge-device-ca.cert.pem
        - EdgeHubConnectionString= ###myconnectionstring###
        expose:
        - 62222/tcp
        hostname: publisher
        image: mcr.microsoft.com/iotedge/opc-publisher:latest
        labels:
            iotedgehubdev: ''
        network_mode: host
        networks:
            azure-iot-edge-dev: null
            host: {}
        ports:
        - 62222:62222/tcp
        restart: always
        volumes:
        - source: edgemoduledev
           target: /mnt/edgemodule
           type: volume
networks:
    azure-iot-edge-dev:
        external: true
    host:
        external: true
volumes:
    edgehubdev:
        name: edgehubdev
    edgemoduledev:
        name: edgemoduledev
```
