### ISSUE TITLE
Environement Variables are not working

### ISSUE THREAD

**Issue by Fredborg** [Azure/iotedgehubdev#265]
Hi,

I believe Environment Variables doesnt work at all in the EdgeHub Dev simulator.

I tried a simple test. I created a new empty module called EnvVariableModule. In deployment.debug.template.json i configured the module with 1 Environment Variable called ENV_VAR like so:

`"EnvVariableModule": { "version": "1.0.0", "type": "docker", "status": "running", "restartPolicy": "always", "settings": { "image": "${MODULEDIR<../EnvVariableModule>.debug}", "createOptions": { "Env": [ "ENV_VAR=MyCoolVariable" ] } } } }`

In program.cs I added the following line of code to retrieve the value of ENV_VAR like so:

string environmentVar = Environment.GetEnvironmentVariable("ENV_VAR");

When starting up environmentVar = null

Why is this not working?

**Comment by SLdragon** [comment]
Hi, @Fredborg, I think your env settings is not correct, please follow the example below to setup environment variables:

```
"Module_Name": {
    "version": "1.0",
    "type": "docker",
    "status": "running",
    "restartPolicy": "always",
    "settings": {
        "image": "${MODULEDIR<../EnvVariableModule>.debug}",
        "createOptions": {}
    },
    "env": {
        "ENV_VAR": {
            "value": "MyCoolVariable"
        }
    }
}
```

**Comment by SLdragon** [comment]
Hi, @Fredborg, I also tested your settings, and it works, here is the sample config:

sample module:
```
"SimulatedTemperatureSensor": {
    "version": "1.0",
    "type": "docker",
    "status": "running",
    "restartPolicy": "always",
    "settings": {
        "image": "mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0",
        "createOptions": {
            "Env": [
                "ENV_VAR=MyCoolVariable"
            ]
        }
    }
}
```

Then in the generated docker-compose.yml file it could contain ENV_VAR environment variable:

```
  SimulatedTemperatureSensor:
    container_name: SimulatedTemperatureSensor
    depends_on:
    - edgeHubDev
    environment:
    - ENV_VAR=MyCoolVariable
    - EdgeModuleCACertificateFile=/mnt/edgemodule/edge-device-ca.cert.pem
    - EdgeHubConnectionString=***
    image: mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
    labels:
      iotedgehubdev: ''
    networks:
      azure-iot-edge-dev: null
    restart: always
    volumes:
    - source: edgemoduledev
      target: /mnt/edgemodule
      type: volume
```

So I think your setting is OK, after starting the module, please check the docker-compose.yml whether contain this env on your machine (you can find the yml file here: C:\ProgramData\iotedgehubdev\data\data\docker-compose.yml)
